# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'back2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Second(object):
    def setupUi(self, Second):
        Second.setObjectName("Second")
        Second.resize(476, 257)
        self.gridLayout = QtWidgets.QGridLayout(Second)
        self.gridLayout.setObjectName("gridLayout")
        self.y_dim_value = QtWidgets.QLineEdit(Second)
        self.y_dim_value.setObjectName("y_dim_value")
        self.gridLayout.addWidget(self.y_dim_value, 7, 6, 1, 1)
        self.grid_label = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grid_label.setFont(font)
        self.grid_label.setObjectName("grid_label")
        self.gridLayout.addWidget(self.grid_label, 1, 4, 1, 2)
        self.x_value = QtWidgets.QLineEdit(Second)
        self.x_value.setObjectName("x_value")
        self.gridLayout.addWidget(self.x_value, 2, 6, 1, 1)
        self.z_dim_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z_dim_name.setFont(font)
        self.z_dim_name.setObjectName("z_dim_name")
        self.gridLayout.addWidget(self.z_dim_name, 8, 5, 1, 1)
        self.OK_button = QtWidgets.QPushButton(Second)
        self.OK_button.setObjectName("OK_button")
        self.gridLayout.addWidget(self.OK_button, 11, 5, 1, 1)
        self.z_dim_value = QtWidgets.QLineEdit(Second)
        self.z_dim_value.setObjectName("z_dim_value")
        self.gridLayout.addWidget(self.z_dim_value, 8, 6, 1, 1)
        self.path_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_name.setFont(font)
        self.path_name.setObjectName("path_name")
        self.gridLayout.addWidget(self.path_name, 1, 0, 2, 1)
        self.z_center_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z_center_name.setFont(font)
        self.z_center_name.setObjectName("z_center_name")
        self.gridLayout.addWidget(self.z_center_name, 4, 5, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Second)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 10, 0, 1, 7)
        self.rec_chain_value = QtWidgets.QLineEdit(Second)
        self.rec_chain_value.setObjectName("rec_chain_value")
        self.gridLayout.addWidget(self.rec_chain_value, 7, 2, 1, 1)
        self.x_center_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_center_name.setFont(font)
        self.x_center_name.setObjectName("x_center_name")
        self.gridLayout.addWidget(self.x_center_name, 2, 5, 1, 1)
        self.spacing_value = QtWidgets.QLineEdit(Second)
        self.spacing_value.setObjectName("spacing_value")
        self.gridLayout.addWidget(self.spacing_value, 9, 5, 1, 2)
        self.y_value = QtWidgets.QLineEdit(Second)
        self.y_value.setObjectName("y_value")
        self.gridLayout.addWidget(self.y_value, 3, 6, 1, 1)
        self.receptor_value = QtWidgets.QLineEdit(Second)
        self.receptor_value.setObjectName("receptor_value")
        self.gridLayout.addWidget(self.receptor_value, 3, 1, 2, 2)
        self.y_center_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_center_name.setFont(font)
        self.y_center_name.setObjectName("y_center_name")
        self.gridLayout.addWidget(self.y_center_name, 3, 5, 1, 1)
        self.path_value = QtWidgets.QLineEdit(Second)
        self.path_value.setObjectName("path_value")
        self.gridLayout.addWidget(self.path_value, 1, 1, 2, 2)
        self.y_dim_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_dim_name.setFont(font)
        self.y_dim_name.setObjectName("y_dim_name")
        self.gridLayout.addWidget(self.y_dim_name, 7, 5, 1, 1)
        self.exit2_button = QtWidgets.QPushButton(Second)
        self.exit2_button.setObjectName("exit2_button")
        self.gridLayout.addWidget(self.exit2_button, 11, 6, 1, 1)
        self.x_dim_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_dim_name.setFont(font)
        self.x_dim_name.setObjectName("x_dim_name")
        self.gridLayout.addWidget(self.x_dim_name, 6, 5, 1, 1)
        self.x_dim_value = QtWidgets.QLineEdit(Second)
        self.x_dim_value.setObjectName("x_dim_value")
        self.gridLayout.addWidget(self.x_dim_value, 6, 6, 1, 1)
        self.rec_chain_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rec_chain_name.setFont(font)
        self.rec_chain_name.setObjectName("rec_chain_name")
        self.gridLayout.addWidget(self.rec_chain_name, 7, 0, 1, 2)
        self.LigandButton = QtWidgets.QToolButton(Second)
        self.LigandButton.setObjectName("LigandButton")
        self.gridLayout.addWidget(self.LigandButton, 5, 3, 1, 1)
        self.receptor_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.receptor_name.setFont(font)
        self.receptor_name.setObjectName("receptor_name")
        self.gridLayout.addWidget(self.receptor_name, 3, 0, 2, 1)
        self.ligand_name = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ligand_name.setFont(font)
        self.ligand_name.setObjectName("ligand_name")
        self.gridLayout.addWidget(self.ligand_name, 5, 0, 1, 1)
        self.ligand_value = QtWidgets.QLineEdit(Second)
        self.ligand_value.setObjectName("ligand_value")
        self.gridLayout.addWidget(self.ligand_value, 5, 1, 1, 2)
        self.api_name = QtWidgets.QLabel(Second)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 149, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.api_name.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.api_name.setFont(font)
        self.api_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.api_name.setObjectName("api_name")
        self.gridLayout.addWidget(self.api_name, 0, 0, 1, 7)
        self.z_value = QtWidgets.QLineEdit(Second)
        self.z_value.setObjectName("z_value")
        self.gridLayout.addWidget(self.z_value, 4, 6, 1, 1)
        self.spacing_label = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spacing_label.setFont(font)
        self.spacing_label.setObjectName("spacing_label")
        self.gridLayout.addWidget(self.spacing_label, 9, 4, 1, 1)
        self.dim_label = QtWidgets.QLabel(Second)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dim_label.setFont(font)
        self.dim_label.setObjectName("dim_label")
        self.gridLayout.addWidget(self.dim_label, 5, 4, 1, 2)
        self.ReceptorButton = QtWidgets.QToolButton(Second)
        self.ReceptorButton.setObjectName("ReceptorButton")
        self.gridLayout.addWidget(self.ReceptorButton, 3, 3, 2, 1)
        self.PathButton = QtWidgets.QToolButton(Second)
        self.PathButton.setObjectName("PathButton")
        self.gridLayout.addWidget(self.PathButton, 1, 3, 2, 1)
        self.label = QtWidgets.QLabel(Second)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)

        self.retranslateUi(Second)
        QtCore.QMetaObject.connectSlotsByName(Second)

    def retranslateUi(self, Second):
        _translate = QtCore.QCoreApplication.translate
        Second.setWindowTitle(_translate("Second", "Form"))
        self.grid_label.setText(_translate("Second", "Gridbox center:"))
        self.z_dim_name.setText(_translate("Second", "Z-dimension:"))
        self.OK_button.setText(_translate("Second", "OK"))
        self.path_name.setText(_translate("Second", "Path:"))
        self.z_center_name.setText(_translate("Second", "Z-center:"))
        self.x_center_name.setText(_translate("Second", "X-center:"))
        self.y_center_name.setText(_translate("Second", "Y-center:"))
        self.y_dim_name.setText(_translate("Second", "Y-dimension:"))
        self.exit2_button.setText(_translate("Second", "Exit"))
        self.x_dim_name.setText(_translate("Second", "X-dimension:"))
        self.rec_chain_name.setText(_translate("Second", "Receptor chain to delete:"))
        self.LigandButton.setText(_translate("Second", "..."))
        self.receptor_name.setText(_translate("Second", "Receptor file:"))
        self.ligand_name.setText(_translate("Second", "Ligand file:"))
        self.api_name.setText(_translate("Second", "                            FitDock"))
        self.spacing_label.setText(_translate("Second", "       Spacing:"))
        self.dim_label.setText(_translate("Second", "Number of points in:"))
        self.ReceptorButton.setText(_translate("Second", "..."))
        self.PathButton.setText(_translate("Second", "..."))
        self.label.setText(_translate("Second", "            <optional>"))
